trigger:
  branches:
    include:
      - dev

pool:
  name: 'my-PC'


variables:
  AZURE_WEBAPP_NAME: 'your-webapp-name' # Replace with your web app name
  PYTHON_VERSION: '3.11' # Replace with your Python version
  DJANGO_SETTINGS_MODULE: 'WTTRPG.settings' # Replace with your Django settings module
  VIRTUALENV_NAME: 'genv'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    addToPath: true

- script: python -m venv $(VIRTUALENV_NAME)
  displayName: 'Create virtual environment'

- script: |
    source $(VIRTUALENV_NAME)/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source $(VIRTUALENV_NAME)/bin/activate
    python manage.py collectstatic --noinput
    python manage.py migrate
  displayName: 'Run Django management commands'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  artifact: drop

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'gumption-webapp(2154975a-cbdf-4bb8-8d44-a6134adb9acf)' # Replace with your Azure subscription name
    appType: 'webApp'
    appName: '$(AZURE_WEBAPP_NAME)'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    startupCommand: 'source $(VIRTUALENV_NAME)/bin/activate && gunicorn $(DJANGO_SETTINGS_MODULE):application --bind 0.0.0.0:8001 --timeout 600'


