trigger:
  branches:
    include:
      - dev

pool: 'my-PC'
variables:
  - group: vg  # Link the variable group

steps:
# Set up Python environment
- script: |
    python --version
  displayName: 'Check Python version'

# Install dependencies
- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'


# Archive the application
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# Publish the artifact
- publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  artifact: drop

# Download the artifact
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'current'
    artifact: 'drop'
    path: '$(Pipeline.Workspace)/drop/'

# Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'gumption-webapp(2154975a-cbdf-4bb8-8d44-a6134adb9acf)' # Replace with your Azure subscription name
    appType: 'webApp'
    appName: '$(AZURE_WEBAPP_NAME)'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    startupCommand: 'source $(VIRTUALENV_NAME)/bin/activate && gunicorn $(DJANGO_SETTINGS_MODULE):application --bind 0.0.0.0:8001 --timeout 600'