# Generated by Django 5.0.1 on 2025-06-07 18:30

import create.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArmorName', models.CharField(max_length=100)),
                ('ArmorDescription', models.TextField()),
                ('ArmorStats', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BackgroundName', models.CharField(max_length=30)),
                ('StartingWeaponChoice', models.CharField(max_length=100)),
                ('StartingSupplies', models.CharField(max_length=100)),
                ('StartingBuff', models.CharField(max_length=100)),
                ('StartingDebuff', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapons', models.JSONField(default=list)),
                ('armors', models.JSONField(default=list)),
                ('utilities', models.JSONField(default=list)),
                ('tonics', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languageName', models.CharField(max_length=30)),
                ('languageDescription', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['-languageName'],
            },
        ),
        migrations.CreateModel(
            name='Morals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moralsName', models.CharField(max_length=30)),
                ('moralsDescription', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['-moralsName'],
            },
        ),
        migrations.CreateModel(
            name='OneShotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpFile', models.FileField(upload_to='create/files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=30)),
                ('skillAttribute', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpeciesName', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MagicSchool', models.CharField(max_length=100)),
                ('SpellDescription', models.TextField()),
                ('SpellName', models.CharField(max_length=100)),
                ('ActionCost', models.CharField(max_length=100)),
                ('Range', models.CharField(max_length=100)),
                ('SpellEffect', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StartingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('itemList', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TestPacketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpFile', models.FileField(upload_to='create/files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tonic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TonicName', models.CharField(max_length=100)),
                ('TonicSize', models.CharField(max_length=100)),
                ('TonicDescription', models.TextField()),
                ('ActionCost', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UtilityName', models.CharField(max_length=100)),
                ('UtilityType', models.CharField(max_length=100)),
                ('ActionCost', models.FloatField()),
                ('Range', models.CharField(max_length=100)),
                ('Effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeaponName', models.CharField(max_length=100)),
                ('DamageType', models.CharField(max_length=100)),
                ('ActionCost', models.FloatField()),
                ('Range', models.CharField(max_length=30)),
                ('Damage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('species', models.CharField(choices=create.models.get_races, max_length=30)),
                ('background', models.CharField(choices=create.models.get_backgrounds, max_length=30)),
                ('major_skill_1', models.CharField(choices=create.models.get_skills, max_length=30)),
                ('major_skill_2', models.CharField(choices=create.models.get_skills, max_length=30)),
                ('major_skill_3', models.CharField(choices=create.models.get_skills, max_length=30)),
                ('minor_skill_1', models.CharField(choices=create.models.get_skills, max_length=30)),
                ('minor_skill_2', models.CharField(choices=create.models.get_skills, max_length=30)),
                ('minor_skill_3', models.CharField(choices=create.models.get_skills, max_length=30)),
                ('minor_skill_4', models.CharField(choices=create.models.get_skills, max_length=30)),
                ('minor_skill_5', models.CharField(choices=create.models.get_skills, max_length=30)),
                ('strength', models.IntegerField(choices=create.models.get_pointbuys)),
                ('agility', models.IntegerField(choices=create.models.get_pointbuys)),
                ('intelligence', models.IntegerField(choices=create.models.get_pointbuys)),
                ('gumption', models.IntegerField(choices=create.models.get_pointbuys)),
                ('mysticism', models.IntegerField(choices=create.models.get_pointbuys)),
                ('personality', models.IntegerField(choices=create.models.get_pointbuys)),
                ('weapon_proficiency', models.CharField(choices=create.models.get_weaponprofs, max_length=30)),
                ('class_name', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('mb', models.IntegerField()),
                ('ec', models.IntegerField()),
                ('ap', models.IntegerField()),
                ('initiative', models.IntegerField(default=2)),
                ('sk_crushing', models.IntegerField(default=5)),
                ('sk_shotguns', models.IntegerField(default=5)),
                ('sk_hand', models.IntegerField(default=5)),
                ('sk_athletics', models.IntegerField(default=5)),
                ('sk_crafting', models.IntegerField(default=5)),
                ('sk_slashing', models.IntegerField(default=5)),
                ('sk_pistols', models.IntegerField(default=5)),
                ('sk_archery', models.IntegerField(default=5)),
                ('sk_ropework', models.IntegerField(default=5)),
                ('sk_acrobatics', models.IntegerField(default=5)),
                ('sk_sneak', models.IntegerField(default=5)),
                ('sk_thievery', models.IntegerField(default=5)),
                ('sk_intimidation', models.IntegerField(default=5)),
                ('sk_hunting', models.IntegerField(default=5)),
                ('sk_cooking', models.IntegerField(default=5)),
                ('sk_foraging', models.IntegerField(default=5)),
                ('sk_animalhandling', models.IntegerField(default=5)),
                ('sk_rifles', models.IntegerField(default=5)),
                ('sk_intuition', models.IntegerField(default=5)),
                ('sk_investigation', models.IntegerField(default=5)),
                ('sk_gambit', models.IntegerField(default=5)),
                ('sk_brewing', models.IntegerField(default=5)),
                ('sk_galvanismmagic', models.IntegerField(default=5)),
                ('sk_religion', models.IntegerField(default=5)),
                ('sk_medicine', models.IntegerField(default=5)),
                ('sk_history', models.IntegerField(default=5)),
                ('sk_healingmagic', models.IntegerField(default=5)),
                ('sk_utilitymagic', models.IntegerField(default=5)),
                ('sk_absolutionmagic', models.IntegerField(default=5)),
                ('sk_foolery', models.IntegerField(default=5)),
                ('sk_persuasion', models.IntegerField(default=5)),
                ('sk_barter', models.IntegerField(default=5)),
                ('sk_deceptionmagic', models.IntegerField(default=5)),
                ('sk_ritualmagic', models.IntegerField(default=5)),
                ('sk_destructionmagic', models.IntegerField(default=5)),
                ('sk_performance', models.IntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='create.inventory')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.language')),
                ('morals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.morals')),
                ('starting_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.startingequipment')),
                ('starting_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.weapon')),
            ],
        ),
    ]
