# Generated by Django 5.0.1 on 2024-03-03 18:34

import create.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('race', models.CharField(choices=create.models.get_races, max_length=30)),
            ],
        ),
    ]
