# Generated by Django 5.0.1 on 2024-03-06 17:53

import create.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArmorName', models.CharField(max_length=100)),
                ('ArmorDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BackgroundName', models.CharField(max_length=30)),
                ('StartingWeaponChoice', models.CharField(max_length=100)),
                ('StartingSupplies', models.CharField(max_length=100)),
                ('StartingBuff', models.CharField(max_length=100)),
                ('StartingDebuff', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RaceName', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MagicSchool', models.CharField(max_length=100)),
                ('SpellType', models.CharField(max_length=100)),
                ('SpellDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tonics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TonicName', models.CharField(max_length=100)),
                ('TonicSize', models.CharField(max_length=100)),
                ('TonicDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UtilityName', models.CharField(max_length=100)),
                ('UtilityType', models.CharField(max_length=100)),
                ('ActionCost', models.FloatField()),
                ('Range', models.IntegerField()),
                ('Effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeaponName', models.CharField(max_length=100)),
                ('DamageType', models.CharField(max_length=100)),
                ('ActionCost', models.FloatField()),
                ('Range', models.IntegerField()),
                ('Damage', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='agility',
            field=models.IntegerField(choices=create.models.get_pointbuys, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.CharField(choices=create.models.get_backgrounds, default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(choices=create.models.get_pointbuys, default=0),
            preserve_default=False,
        ),
    ]
