# Generated by Django 5.0.1 on 2025-06-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_perk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perk',
        ),
    ]
