# Generated by Django 5.0.1 on 2025-06-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_delete_perk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perkSkill', models.CharField(max_length=100)),
                ('skillLevel', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
