# Generated by Django 5.0.1 on 2025-06-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_perk'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='perks',
            field=models.ManyToManyField(related_name='characters', to='create.perk'),
        ),
    ]
