# Generated by Django 5.0.1 on 2024-05-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0005_rename_race_species_rename_race_character_species_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moralsName', models.CharField(max_length=30)),
                ('moralsDescription', models.CharField(max_length=300)),
            ],
        ),
    ]
