# Generated by Django 5.0.1 on 2025-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0006_alter_character_perks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='perks',
            field=models.ManyToManyField(default=None, related_name='characters', to='create.perk'),
        ),
    ]
