# Generated by Django 5.0.1 on 2025-06-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0007_alter_character_perks'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='perkName',
            field=models.CharField(default='perk', max_length=100),
            preserve_default=False,
        ),
    ]
