# Generated by Django 5.0.1 on 2024-05-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0007_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-languageName']},
        ),
        migrations.AddField(
            model_name='character',
            name='language',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='create.language'),
            preserve_default=False,
        ),
    ]
