# Generated by Django 5.0.1 on 2025-08-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0008_perk_perkname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClothingName', models.CharField(max_length=100)),
                ('ClothingDescription', models.TextField()),
                ('ClothinStats', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Armor',
        ),
    ]
