# Generated by Django 5.0.1 on 2024-05-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0008_alter_language_options_character_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='language',
            field=models.CharField(max_length=10),
        ),
    ]
