# Generated by Django 5.0.1 on 2025-08-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0009_clothing_delete_armor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='ClothinStats',
            new_name='ClothingStats',
        ),
    ]
