# Generated by Django 5.0.1 on 2024-05-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0009_alter_character_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.RemoveField(
            model_name='character',
            name='language',
        ),
    ]
