# Generated by Django 5.0.1 on 2025-08-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0010_rename_clothinstats_clothing_clothingstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='armors',
            new_name='clothing',
        ),
    ]
