# Generated by Django 5.0.1 on 2025-09-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0011_rename_armors_inventory_clothing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='ActionCost',
            field=models.TextField(),
        ),
    ]
