# Generated by Django 5.0.1 on 2024-05-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0012_character_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morals',
            options={'ordering': ['-moralsName']},
        ),
        migrations.AddField(
            model_name='character',
            name='morals',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='create.morals'),
            preserve_default=False,
        ),
    ]
