# Generated by Django 5.0.1 on 2025-09-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0012_alter_utilities_actioncost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysticalWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeaponName', models.CharField(max_length=100)),
                ('DamageType', models.CharField(max_length=100)),
                ('ActionCost', models.CharField(max_length=100)),
                ('Range', models.CharField(max_length=30)),
                ('Damage', models.CharField(max_length=100)),
                ('ExtraEffect', models.TextField()),
            ],
        ),
    ]
