# Generated by Django 5.0.1 on 2024-05-21 14:52

import create.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0013_alter_morals_options_character_morals'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weaponprof',
            field=models.CharField(choices=create.models.get_weaponprofs, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
