# Generated by Django 5.0.1 on 2025-09-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0013_mysticalweapon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysticalweapon',
            old_name='WeaponName',
            new_name='MysticalWeaponName',
        ),
    ]
