# Generated by Django 5.0.1 on 2024-05-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0014_character_weaponprof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='weaponprof',
            new_name='weapon_proficiency',
        ),
    ]
