# Generated by Django 5.0.1 on 2025-09-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0014_rename_weaponname_mysticalweapon_mysticalweaponname'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='mysticalweapons',
            field=models.JSONField(default=list),
        ),
    ]
