# Generated by Django 5.0.1 on 2024-06-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0015_rename_weaponprof_character_weapon_proficiency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='majorskill1',
            new_name='major_skill_1',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='majorskill2',
            new_name='major_skill_2',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='majorskill3',
            new_name='major_skill_3',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='minorskill1',
            new_name='minor_skill_1',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='minorskill2',
            new_name='minor_skill_2',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='minorskill3',
            new_name='minor_skill_3',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='minorskill4',
            new_name='minor_skill_4',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='minorskill5',
            new_name='minor_skill_5',
        ),
        migrations.AddField(
            model_name='character',
            name='class_name',
            field=models.CharField(default='class', max_length=30),
            preserve_default=False,
        ),
    ]
