# Generated by Django 5.0.1 on 2025-09-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0015_inventory_mysticalweapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='spells',
            field=models.JSONField(default=list),
        ),
    ]
