# Generated by Django 5.0.1 on 2024-08-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0018_character_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ap',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='ec',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='initiative',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='character',
            name='mb',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
