# Generated by Django 5.0.1 on 2024-09-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0020_character_sk_absolutionmagic_character_sk_acrobatics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sk_performance',
            field=models.IntegerField(default=1),
        ),
    ]
