# Generated by Django 5.0.1 on 2024-09-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0021_character_sk_performance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='sk_handtohand',
            new_name='sk_hand',
        ),
    ]
