# Generated by Django 5.0.1 on 2024-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0024_startingequipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='starting_weapon',
            field=models.CharField(max_length=30),
        ),
    ]
