# Generated by Django 5.0.1 on 2024-10-25 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0025_alter_character_starting_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='starting_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.startingequipment'),
        ),
        migrations.AlterField(
            model_name='character',
            name='starting_weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.weapon'),
        ),
    ]
