# Generated by Django 5.0.1 on 2024-11-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0026_alter_character_starting_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='Range',
            field=models.CharField(max_length=30),
        ),
    ]
