# Generated by Django 5.0.1 on 2024-11-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0027_alter_weapon_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='SpellType',
            new_name='Range',
        ),
        migrations.AddField(
            model_name='spell',
            name='ActionCost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='SpellEffect',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='SpellName',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
