# Generated by Django 5.0.1 on 2024-11-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0028_rename_spelltype_spell_range_spell_actioncost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='ActionCost',
            field=models.CharField(max_length=100),
        ),
    ]
