# Generated by Django 5.0.1 on 2024-11-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0030_alter_utilities_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='ArmorStats',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
