# Generated by Django 5.0.1 on 2024-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0031_armor_armorstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tonic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TonicName', models.CharField(max_length=100)),
                ('TonicSize', models.CharField(max_length=100)),
                ('TonicDescription', models.TextField()),
                ('ActionCost', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tonics',
        ),
    ]
