# Generated by Django 5.0.1 on 2024-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0033_alter_tonic_actioncost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPacketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpFile', models.FileField(upload_to='create/files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
