# Generated by Django 5.0.1 on 2024-12-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0034_testpacketfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='sk_slashingmelee',
            new_name='sk_slashing',
        ),
    ]
