# Generated by Django 5.0.1 on 2025-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0035_rename_sk_slashingmelee_character_sk_slashing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterPK', models.IntegerField()),
                ('weapons', models.JSONField(default=list)),
                ('armors', models.JSONField()),
                ('utilities', models.JSONField()),
                ('tonics', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='OneShotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpFile', models.FileField(upload_to='create/files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
