# Generated by Django 5.0.1 on 2025-04-07 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0036_inventory_oneshotfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='create.inventory'),
        ),
    ]
