# Generated by Django 5.0.1 on 2025-04-07 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0037_character_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='create.inventory'),
        ),
    ]
