# Generated by Django 5.0.1 on 2025-04-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0038_alter_character_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='characterPK',
        ),
    ]
