# Generated by Django 5.0.1 on 2025-04-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0039_remove_inventory_characterpk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='armors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tonics',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='utilities',
            field=models.JSONField(default=list),
        ),
    ]
